services:
  core-models:
    image: ghcr.io/credona/age-decision-core:v2.2.2
    working_dir: /app
    command: python scripts/models/download_models.py
    volumes:
      - core-models:/app/models

  antispoof-models:
    image: ghcr.io/credona/age-decision-antispoof:v2.2.2
    working_dir: /app
    command: python scripts/models/download_models.py
    volumes:
      - antispoof-models:/app/antispoof/models

  age-decision-core:
    image: ghcr.io/credona/age-decision-core:v2.2.2
    depends_on:
      core-models:
        condition: service_completed_successfully
    volumes:
      - core-models:/app/models

  age-decision-antispoof:
    image: ghcr.io/credona/age-decision-antispoof:v2.2.2
    depends_on:
      antispoof-models:
        condition: service_completed_successfully
    volumes:
      - antispoof-models:/app/antispoof/models

  age-decision-api:
    image: ghcr.io/credona/age-decision-api:v2.2.2
    depends_on:
      - age-decision-core
      - age-decision-antispoof
    environment:
      AGE_DECISION_CORE_URL: http://age-decision-core:8000
      AGE_DECISION_ANTISPOOF_URL: http://age-decision-antispoof:8001

  age-decision-js:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - age-decision-api
    working_dir: /app
    command: sh -c "npm run test:integration"

volumes:
  core-models:
  antispoof-models:
